class Answer_All():
    unit_1 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4902", 0,
                  ["B", "A", "D", "C", "B"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4903", 1,
                  ["D", "A", "G", "F", "B", "C", "H", "E"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4906", 1,
                  ["the application of science to solve real-world problems",
                   "people who are trained to solve real world problems", "mechanical engineering", "civil engineering",
                   "chemical engineering", "petroleum engineering", "electrical/electronic engineering",
                   "aerospace engineering", "investigate that which already is", "create that which has never been",
                   "two master races that complement each other"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4907", 1,
                  ["a stream of science", "real-world problem", "particle accelerator", "physical structure",
                   "rechargeable battery", "modern industry", "crude oil", "renewable energy", "hierarchical dispute",
                   "multiple theory"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4908", 1,
                  ["take a stance for", "pertain to", "in high demand", "leave a mark on", "in every sense"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4909", 2,
                  ["这些机器复杂程度和大小各异，每台机器都是为特定的目的而设计制造的。", "氯化净水和使用化学物质处理金属都是化学工程成就的副产品，这些成就使世界变得美好。",
                   "现代自动化更需要电气工程，而可再生能源的出现使电气工程师成为现代世界的救世主。", "基本上来说，科学家发现世界存在的现象，然而，我们不能利用它，除非我们了解它。",
                   "科学家帮助我们更好地解码事物，而工程师则利用这些发现创造不存在的东西。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4910", 2, [
            "Although the word engineer always arouses a sense of pride and it's worth being an engineer, many people still lack a deeper understanding of what engineering is from a historical point of view. Engineering is a stream of science that has helped humans shape the world and will continue to do so. As the author tells us, engineering is the application of science to solve real-word problems, and engineers, as practitioners of engineering, are problem solvers who use their expertise in science. As we trace back in time, we can easily see the influences of engineers, past and present, on the world we are living in. Engineers are the special spectrum of people who take delight in creating order from disorder and move the world forward.Engineering is a broad field that is divided into various disciplines and sub-disciplines, but there exist only six main categories: mechanical engineering, civil engineering, chemical engineering, petroleum engineering, electrical/electronic engineering, and aerospace engineering. Engineers differ from scientists in that they create that which has never been, while scientists investigate that which already is. However, both scientists and engineers complement each other and make contributions to our society. Although engineering is a great field to get into, an engineering career might not be a good fit for everyone."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4911", 1,
                  ["B", "D", "E", "C", "A"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4912", 0,
                   ["B", "D", "A", "B", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4914", 1,
                   ["exception", "norm", "what makes this news so exciting",
                    "water harvesting, purification and conservation",
                    "thermal management, energy conversion, and storage", "diversity", "phenomenal",
                    "what they have achieved as researchers and professors"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitFillBlank.aspx?UnitTreeID=4918", 1,
                   ["是……的典型；代表", "He studied and taught at UC Berkeley, he typified the CEO as an educator.",
                    "使……大为惊讶；使印象深刻",
                    "And somehow as a summer student, I found my way into that course and I was blown away.", "副产品",
                    "Andy was at Fairchild and Silicon Valley—the silicon is not an accident, we call all the semiconductor spin-offs from Fairchild the fair children, and Andy was, I believe, badge number three employee number two of the most important of all of those which was Intel. ",
                    "（佩戴在身上以显示工作单位的）徽章；证章",
                    "Andy was at Fairchild and Silicon Valley—the silicon is not an accident, we call all the semiconductor spin-offs from Fairchild the fair children, and Andy was, I believe, badge number three employee number two of the most important of all of those which was Intel.",
                    "支点，转折点",
                    "Andy led some very tough strategic decisions, pivots someone called them, in Intel’s history such as getting out of dynamic RAM memories to make microprocessors and EEPROMs, or another one less well-known is once they were in the microprocessor business they were losing the 16-bit microprocessor battles to Motorola and to Zilog.",
                    "=electrically erasable programmable read-only memory电可擦可编程只读存储器",
                    "Andy led some very tough strategic decisions, pivots someone called them, in Intel’s history such as getting out of dynamic RAM memories to make microprocessors and EEPROMs, or another one less well-known is once they were in the microprocessor business they were losing the 16-bit microprocessor battles to Motorola and to Zilog.",
                    "晶圆，晶片",
                    "I mean, think of this, thousands of people had to get millions of lines exactly right on every chip, on every wafer or nothing worked.",
                    "使大众化", "Andy Grove democratized computing, he made it affordable to everyone.", "摩尔定律",
                    "He put dozens of microprocessors in all of our homes, so whether it’s managing solar panels so you can get power in Africa, or making refrigerators more efficient, or automobiles safer, or blood chemistry more analyzed, the microprocessor I think is the most important technological invention of the last three or so decades, and Andy Grove is the man who took Moore’s law and made it happen."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4915", 1,
                   ["非，无", "反对；抗……", "二，双", "反对；相反", "网络的；计算机的", "对立，相反", "二，双", "穿过；二者之间", "不；非；相对；相反",
                    "进入……之中；使……进入状态", "外部的；外面", "在上；超出；高于", "在……之间；相互", "在里面，在内部", "向内；入内", "坏的；不良地", "错，误，坏", "许多",
                    "新的", "超过；过度；出去", "过度地", "之后，在后", "先于，在前", "第一，主要；原始", "假，伪", "类似；准", "半", "低于；亚，接近；从属", "在上；超出",
                    "共同；相同", "远距离的", "横穿；从……到……", "超出，超过；极端", "可被……的，能被……的", "动作的承受者", "表示“小”", "表示“小”；“女性”", "倍数",
                    "防……的", "向……", "方向，方式，状态"]]
    }

    unit_2 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4929", 0,
                  ["D", "A", "A", "C", "B"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4930", 1,
                  ["E", "C", "G", "F", "D", "H", "B", "A"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4934", 1,
                  ["Hadoop-based", "an established technology", "The Era of Multi-Cloud",
                   " support applications and platforms across multiple clouds", "The Era of Machine Learning",
                   "focus on analytic models, algorithms, model training, deep learning, and the ethics of algorithmic and deep learning technologies",
                   "The Era of Real-Time and Ubiquitous Context",
                   "timely updates both from an analytic and engagement perspective",
                   "Hadoop still has its place in enterprise data.",
                   "The need for multi-cloud analytics and data visualization is greater than ever.",
                   "Machine learning and data science are the next generation of analytics and will require their own new data management efforts.",
                   "Real-time and ubiquitous context needs to be seen as a data challenge as well as a collaborative and technological challenge.",
                   "Use the entirety of big data as a business asset to support job-based context, machine learning, and real-time interaction."]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4935", 1,
                  ["established technology", "machine learning", "analytic model", "deep learning", "edge observation",
                   "extended reality", "behavioral feedback", "data integration", "data modeling",
                   "strategic advantage"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4936", 1,
                  ["interact with", "come to an end", "bring into being", "speak to", "figure out"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4937", 2,
                  ["随着大数据的逝去，我们继续向前推进，照管大数据时代的后裔，包括多云时代、机器学习时代、实时泛在的数据环境时代。",
                   "机器学习需要做大量相同的工作来创建用于分析的纯净数据，但也需要额外的数学、商业和伦理环境来创建持久和长期的价值。",
                   "实时分析的有效使用需要广泛的业务数据来提供适当的整体环境，以及依据数据或依据需求来执行分析。",
                   "随着大数据时代的结束，我们现在可以更少地关注收集大量数据的机制，而更多地关注实时处理、分析和与大量数据实时交互的挑战。",
                   " 这里最重要的考虑因素是使用不能很好服务于业务的数据，因为这些数据样本量小、缺乏数据源、定义不清、数据环境不佳或算法和分类假设不准确。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4938", 2, [
            "As the maturity of the first generation of Hadoop-based big data, we are heading for a new era of big data, which include the era of multi-cloud, era of machine learning, and the era of real-time and ubiquitous context. The era of multi-cloud supports applications and platforms across multiple clouds to meet the increasing need for supporting continuous delivery and business continuity. The era of machine learning focuses on analytic models, algorithms, model training, deep learning, and the ethics of algorithmic and deep learning technologies to create lasting and long-term value. The era of real-time and ubiquitous context is characterized as providing timely updates and in-site, in-time, in-action context needed for effective behavioral feedback.As we progress to new eras driven by big data, we should bear in mind that Hadoop still has its place in enterprise data, but the need for multi-cloud analytics and data visualization is greater than ever; machine learning and data science are the next generation of analytics and will require their own new data management efforts; real-time and ubiquitous context needs to be seen as a data challenge as well as a collaborative and technological challenge.In conclusion, as the era of big data comes to an end, the entirety of big data should be used as a business asset to support job-based context, machine learning, and real-time interaction."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4940", 1,
                  ["D", "C", "A", "E", "B"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4941", 0,
                   ["B", "C", "D", "D", "A"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4942", 1,
                   ["keep an end-to-end inventory of critical data", "maximize the value of their information",
                    "analyze equipment failures, production bottlenecks, supply chain deficiencies", " decision-making",
                    " paramount",
                    "ensure compliance with data quality standards, oversee equipment performance and review production process efficiency"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4945", 1, ["收集",
                                                                                                    "Online, offline every which way-line you just can’t help producing the stuff, and there’s a huge drive to collect it all because intelligence can be gleaned from it.",
                                                                                                    "强烈要求",
                                                                                                    "This is the data that every company and government is now clamoring to collect because knowledge is power and everybody’s job becomes easier the more they know about everybody else.",
                                                                                                    "提取",
                                                                                                    "A company can take its customer database, extract and analyze information on the purchasing habits of customers and cross-reference that data set with increasingly available data on income, property ownership, age, and other specific sets.",
                                                                                                    "聚集",
                                                                                                    "Searching, aggregating, and cross-referencing in order to generate intelligence. ",
                                                                                                    "无害的",
                                                                                                    "Except in cross-referencing data sets like this, big data analytics are putting together pieces of data that in isolation is seemingly innocuous, but in combination, produce a detailed picture of troubling accuracy for everyone across all transactions, all communications, and all movements. ",
                                                                                                    "模式",
                                                                                                    "If you don’t fit the mold or you act out of the norm or appear to be from an undesirable grouping, you’ll be placed into boxes that would be nearly impossible to escape from.",
                                                                                                    "吊销，撤销",
                                                                                                    "Other serious and ruinous error can happen like having your driving license mistakenly revoked, your benefits canceled, electoral participation denied, even arrests made and being detained. ",
                                                                                                    "大幅度削减",
                                                                                                    "As slashed budgets lead to increased staff cuts, automated systems have moved from acting as simple administrative tools to primary decision-makers. ",
                                                                                                    "分配",
                                                                                                    "Several cities across the US are using such tools to analyze crime statistics, map where crimes are more likely to occur and allocate resources accordingly."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4947", 2,
                   ["现在，斯坦福大学的研究人员已经证明，几层原子厚度的材料，像一张张纸一样叠放在热点上，可以提供和厚100倍的玻璃一样的隔热效果。",
                    "尽管美国国家航空航天局（NASA）和其他初创企业开发了无人机跟踪和飞行管理系统，但推动无人驾驶和便捷性的努力可能会遭遇普通民众一致的抵制。",
                    "周二，由加州大学旧金山分校（UCSF）的语言神经学家Edward Chang领导的研究人员汇报说，他们通过读取测试对象大脑语言中枢的活动，尝试实时解码语音获得成功。",
                    "为了演示这种可穿戴技术，研究人员将传感器固定在一名受试者的手腕和腹部，通过检测他们的皮肤在每次心跳或呼吸时的拉伸和收缩情况，来监测受试者的脉搏和呼吸。",
                    "3D打印技术对于维修老旧的汽车尤其有用，因为老旧的汽车很难找到或根本不存在零部件供应——只要把坏掉的东西拿出来，扫描一下，然后吐出一个新的就行了。"]]
    }

    unit_3 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4958", 0,
                  ["D", "A", "A", "B", "D"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4959", 1,
                  ["H", "E", "D", "C", "A", "F", "G", "B"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4964", 1,
                  ["an umbrella term for immersive technologies",
                   " to highlight why executives should utilize XR in their businesses",
                   "Executives can spot trends by following the money",
                   "The XR industry is maturing, and interest in sectors other than gaming is growing rapidly",
                   "Workforce development is a key opportunity for XR",
                   "XR’s applications in workforce development are varied, among which training is the most relevant one",
                   "XR has many applications for consumer-facing industries",
                   "The adoption of XR technology could benefit workplaces in the long term as millennials begin to dominate the workforce",
                   "Forward-thinking executives should consider incorporating XR into their business plans"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4965", 1,
                  ["augmented reality", "immersive experiences", "venture capital",
                   "the same time period in the previous year", "real-time information", "product design",
                   "retention rate", "virtual showroom", "talent pool", "cutting-edge technology"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4966", 1,
                  ["have been around", "Given that", "trying out", "other than", "make up"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4967", 2,
                  ["高管们可以通过资金的流向来发现趋势，对XR领域——特别是在游戏之外的领域，比如劳动力创新和培训、电子商务应用等——的投资日益增加，这表明有远见的高管很快就会受到沉浸式技术的影响。",
                   "事实上，2018年第四季度全球风险投资交易的价值飙升至17亿美元，是去年同期的三倍。",
                   "此外，百分之九十的受访者认为XR是未来的必然特征，并预测“到2025年，XR的沉浸式技术——包括增强现实、虚拟现实和混合现实——将像移动设备一样无处不在。”",
                   "重点是对XR的投资正在迅速增加，XR技术将被投入更多实际应用，从而增加员工、供应商、合伙人、客户间的联系与协作。",
                   "受访者认为XR在劳动力发展方面的应用将是多样化的，他们认为XR对劳动力发展的好处包括获取实时信息、进行仿真培训、提高产品设计与开发的创造力以及加强远程员工间的协作。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4968", 2, [
            "Business executives should embrace extended reality (XR) technology for its application in various fields in order to maximize future business outcomes. First of all, the investment in XR is rapidly increasing in different areas and sectors, and has no signs of stopping, indicating that immersive technologies will be prevalent in the future and result in more applications. Companies that don’t want to get left behind should start to use XR in ways that best suit their business needs. Second, XR has many case applications. For example, XR is highly applicable to workforce development, employee training, and consumer-facing industries such as e-commerce. XR can offer a wide range of possibilities in every aspect of life and in an ongoing way. Third, a younger and tech-savvy workforce demands cutting-edge technologies such as XR as millennials begin to dominate the workforce. The adoption of XR technology could benefit workplaces in the long term. To sum up, XR is coming. It is a good time for forward-thinking executives to consider entertaining the XR technology."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4971", 1,
                  ["D", "B", "C", "A", "E"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4972", 0,
                   ["C", "B", "A", "D", "D"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4973", 1,
                   ["the main focus", " incorporate virtual reality into its engineering training programmes",
                    " designing, testing, and maintaining engines in the digital realm",
                    "it brings cutting-edge technology to the training programmes", "holograms",
                    " augmented reality", "overlaid over a real engine to show technical information"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4976", 1, ["听觉的",
                                                                                                    "In fact, here I am actually just sitting back in an apartment in New York, and it could be feeding me visual experiences and auditory experiences.",
                                                                                                    "笛卡尔（法国哲学家、数学家）",
                                                                                                    "Descartes, hundreds of years ago, said, “How do you know that you’re not being fooled right now by an evil genius who’s feeding you sensations into your mind to think that all this is going on out there, when in fact, none of it really exists?”",
                                                                                                    "假设",
                                                                                                    "The philosopher Nick Bostrom has argued, in fact, maybe we should take this hypothesis very seriously. ",
                                                                                                    "层次结构",
                                                                                                    "It’s far more probable that I’m somewhere down in the hierarchy of simulated universes.",
                                                                                                    "阐明，解释",
                                                                                                    "I see virtual reality as raising a bunch of new philosophical problems, but at the same time, really illuminating a lot of old philosophical problems and throwing new light on them.",
                                                                                                    "怀疑论",
                                                                                                    "Skepticism about the external world is the view that we don’t know that the external world even exists.",
                                                                                                    "矩阵",
                                                                                                    "And all the things we ordinarily take ourselves to know like that I’m sitting down right now on a chair might well be false, and I don’t know them, because, for example, I could be in a matrix virtual reality which is a mere simulation.",
                                                                                                    "欺骗",
                                                                                                    "But once you actually start to think about virtual reality in some detail, that actually, to me, no longer obvious that this has to be seen as an illusion or as a deception. ",
                                                                                                    "新奇的",
                                                                                                    "It’s a newfangled technology which I might think raises some limited questions in the philosophy of technology."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4979", 2,
                   ["在不久的将来，我们可以期待高概念的可穿戴设备，比如目前正在研发的能读取情绪的亚马逊专利技术，以及让人们无需说话就能交谈的互我（AlterEgo）神经界面。（顺译法）",
                    "对于以往的几代人来说，旧式的体力劳动是一种摆脱贫穷的手段，而技术的进步则摧毁了穷人赖以为生的体力劳动。因此，首先体验到进步之害的是穷人。（逆译法）",
                    "制造过程可以分为单件生产和批量生产。单件生产指的是生产少量的零件，批量生产则是指生产大量相同的零件。（分译法）",
                    "鱼能发电，其强度足以点亮小灯泡，甚至能开动马达，这简直令人难以置信。（综合法）",
                    "例如，对于一个四口之家来说，舒舒服服地坐在家里享受着各种娱乐节目，这比到外面去消遣要更加方便，也更加便宜。（综合法）"]]

    }

    unit_4 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4988", 0,
                  ["A", "B", "A", "A", "B"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4989", 1,
                  ["B", "D", "F", "H", "A", "C", "G", "E"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4994", 1,
                  ["Manufacturing", "production operations", "the use of robots",
                   "increased adoption of augmented reality for training, maintenance, construction and repair",
                   "Energy & utilities", "energy production, transmission, distribution, and usage",
                   "smart grid and energy management", "increased lifespan of battery-dependent devices",
                   "the use of drones to monitor and maintain transmission of production assets", "Retail",
                   "improved mobile shopping experience", "VR dressing rooms",
                   "mobile AR experiences in stores and at home", "Financial services", "internal operations",
                   "customer engagement", "payments transactions",
                   "wearable devices to authenticate user identity instantly and accurately", "Media & entertainment",
                   "mobile media, mobile advertising, home broadband, TV", "emerging interactive technologies",
                   "increased download speed", "Healthcare",
                   "faster and more efficient networks for the healthcare system", "remote monitoring devices",
                   "remote robotic surgery", "Transportation",
                   "increased visibility and control over transportation systems", "V2V and V2I communication",
                   "Education", "AR/VR educational platforms", "Cloud computing", "better cloud computing experience",
                   "Public safety", "assisting emergency situations", "information sharing", "the use of drones",
                   "an enhanced network of sensors, cameras, and other automated devices"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4995", 1,
                  ["production operation", "manufacturing industry", "mobile network", "low latency", "smart grid",
                   "wearable device", "loading time", "remote monitoring", "cloud computing", "central server"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4996", 1,
                  ["open the door to", "assist in", "had been watered down / were watered down", "is poised to",
                   "keep up with"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4997", 2,
                  ["可穿戴设备可以通过5G连接与金融服务部门共享生物识别数据，从而及时准确地验证用户身份。", "5G必将从多方面颠覆包括移动媒体、移动广告、家庭宽带和电视在内的媒体和娱乐业。",
                   "在浏览社交媒体、游戏、流媒体音乐以及下载电影和节目方面，5G预计每月将为人们节省23个小时的加载时间。",
                   "根据Ovum的一项研究，未来十年，5G技术支持的新服务和应用将给全球媒体行业带来累计达到7650亿美元的惊人收入。",
                   "Next Galaxy和Nicklaus儿童医院的一项研究发现，培训中使用VR技术可以令医务人员记住高达80%的授课内容，而通过传统方式培训，医务人员只能记住20%。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4998", 2, [
            " Ten industries are discussed where 5G technology can bring about disruptions. In the manufacturing industry, 5G improves the flexibility, efficiency and safety of production operations, enabling manufacturers to enhance smart factories. In the energy and utilities industry, 5G provides innovative solutions to various areas in energy management and widens the potential application of smart grids. In the retail industry, the extremely fast data speeds will enhance the mobile shopping experience, and develop innovative ways of customer engagement that incorporate AR/VR technologies. In the financial services, 5G could accelerate a number of mobile operations and assist in real-time data transmission. In the media and entertainment industry, 5G revolutionizes many areas via the exponential increase in the download speed and unprecedented virtual consumption experience. In the healthcare industry, not only will 5G be capable of handling the massive data load, but it will also facilitate the remote monitoring devices and remote surgery procedures. In the transportation industry, 5G offers new insights into smart transportation systems such as V2V and V2I communications. In the education industry, 5G has the potential to transform traditional educational methods and enrich classroom learning experience by leveraging AR/VR technologies particularly in high-risk educational settings. In the cloud computing, 5G’s low latency and high throughput could improve cloud computing experience. In the public safety industry, 5G could enhance public safety capabilities thereby improving emergency response and information sharing."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5000", 1,
                  ["C", "B", "E", "A", "D"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5001", 0,
                   ["D", "B", "C", "A", "D"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5002", 1,
                   ["teleport", "in an instant", "scenarios", "teleportation can be achieved", "philosophy", "scanned",
                    "transmitted", "build an entirely new body out of different materials",
                    "when two or more particles are forced to hold mutually exclusive states", "simultaneously"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5007", 1,
                   ["延迟", "The new standard means devices can communicate with each other with no lag.", "零延迟",
                    "You know how when you write with a pen, you see it as it happens, that zero latency, that’s pretty much what 5G can do. No waiting.",
                    "基础设施", "First, we need a whole new infrastructure.", "毫米波",
                    "The 5G standard uses millimeter waves, which are a lot shorter than the wavelengths 4G uses.",
                    "天线",
                    "To ensure a reliable 5G signal, there needs to be a lot of 5G cell towers and antennas everywhere.",
                    "节点", "Each node, or, you know, mini cell tower needs some kind of connection to it.", "光缆",
                    "That means laying down fiber optic cables.", "推出",
                    "While 5G is being rolled out, it is very slow and in limited areas. ", "拥挤",
                    "I do estimate that eventually, even 5G will be congested with the number of people connecting to it and also the extra stuff that’s going to be used for 5G."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5011", 1,
                   ["B [topic cue]", "G [structure cue]", "E [organisation cue—listing]",
                    "C [organisation cue—listing]", "A [organisation cue—giving examples]", "D [concluding cue]",
                    "F [transition cue]"]]

    }

    unit_5 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5020", 0,
                  ["C", "C", "B", "D", "C"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5021", 1,
                  ["D", "E", "B", "A", "G", "H", "C", "F"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5027", 1,
                  ["one no human would think to make", "solutions to tough problems", "Ai Build", "music industry",
                   "their creative process", "even themselves", "Reeps One’s battle with an AI opponent",
                   "society is more likely to engage with", " gaming industry",
                   "practitioners can focus on more creative ones", "self-controlled", "into our work as a contributor",
                   "challenging the possibilities of creation", "giving us more understanding of creativity"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5028", 1,
                  ["winning strategy", "additive manufacturing", "production process", "deep-learning programme",
                   "creative output", "computer-generated", "visual artist", "recommendation algorithm",
                   "abstract thinking", "episodic memory"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5029", 1,
                  ["more of", "a collection of", "takes into account", "engage with", "take part"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5030", 2,
                  ["虽然AlphaGo可以说是领先了这个时代很多年，但是人工智能正在迅速进入我们的日常生活，其发展已经开始改变和辅助创作过程，同时也在挑战我们所认为的“创造性思维”。",
                   "随着备选解决方案的增多，我们无法做出有效一致的决定。", "人工智能解决了这个问题，它帮助像Cam和Desyllas这样的设计师加快思考过程，丰富创意方案，从而制作出更好的设计。",
                   "Ai Build公司使用人工智能实现生产过程自动化，从而减少了材料消耗，降低了劳工成本，创造出了曾经无法想象也无法实现的复杂的设计作品。",
                   "然而人工智能在今时今日的创作实践中却是自我约束的，这表示人工智能是在一个受控的环境中工作，按照人们设定好的程序运行。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5031", 2, [
            " Artificial intelligence (AI) is spreading through our lives, and it has made a surprising impact on human creativity. To begin with, a case in point is AlphaGo. The Google system relied on its own creative intelligence to design a winning chess move and beat the world’s reigning champion at Go in 2016. Nowadays AI continues influencing creativity across industries. In the manufacturing industry, AI can learn creativity from mountains of datasets and quickly produce large arrays of solutions to tough problems. In the music industry, AI gives musicians the ability to better understand their own creative process and themselves so as to help them become even more creative. Besides, music pieces generated by AI are socially accepted as well. Similarly, AI in the visual art industry is also adopted as a tool to shape creative strategies. Arts, with the assistance of AI, now can be tailored to popular tastes. In the gaming industry, AI releases human from mundane tasks so that people can focus on more creative ones. Creative as it seems, what AI does is controlled in nature. In the near future, AI is expected to become more creative and contributing, and even interact with players in the games. To conclude, AI is challenging the possibilities of creation and giving us more understanding of creativity."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5033", 1,
                  ["C", "A", "B", "E", "D"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5034", 0,
                   ["D", "B", "C", "A", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5035", 1,
                   ["enhance customer satisfaction, speed up decision-making, and reduce inefficiencies",
                    "assembling AI institutions to guide governance, often consulting with the private sector and civil society",
                    "unemployment narratives", "counterbalanced ", "enhance and augment human work"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5039", 1, ["神经科学家",
                                                                                                    "Some neuroscientists believe that any sufficiently advanced system can generate consciousness.",
                                                                                                    "使享有权利",
                                                                                                    "Consciousness entitles beings to have rights because it gives a being the ability to suffer.",
                                                                                                    "侵犯，侵害",
                                                                                                    "For example, we dislike pain because our brains evolved to keep us alive, to stop us from touching a hot fire or to make us run away from predators, so we came up with rights that protect us from infringements that cause us pain.",
                                                                                                    "拆卸",
                                                                                                    "Would it mind being dismantled if it had no fear of death? ",
                                                                                                    "人类例外论",
                                                                                                    "Our whole human identity is based on the idea of human exceptionalism that we are special, unique snowflakes entitled to dominate the natural world.",
                                                                                                    "自动机，自动之物",
                                                                                                    "In the midst of the Scientific Revolution, René Descartes argued that animals were mere automata, robots if you will.",
                                                                                                    "令人厌恶的",
                                                                                                    "As such, injuring a rabbit was about as morally repugnant as punching a stuffed animal. ",
                                                                                                    "犯罪者",
                                                                                                    "And many of the greatest crimes against humanity were justified by their perpetrators on the grounds that the victims were more animal than civilized human.",
                                                                                                    "有感觉的",
                                                                                                    "If we can coerce a sentient AI possibly through programmed torture into doing as we please, the economic potential is unlimited. "]]

    }

    unit_6 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5051", 0,
                  ["C", "B", "A", "D", "C"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5052", 1,
                  ["E", "C", "G", "A", "F", "B", "H", "D"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5057", 1,
                  ["data from connected operations and production systems to learn", "new demands",
                   "efficient and agile system", "production downtime",
                   "predict and adjust to changes in the facility or broader network",
                   "a single, discrete task or process",
                   "self-optimize performance across a broader network, self-adapt to and learn from new conditions in real or near-real time",
                   "its connected nature", " yield, uptime and quality", "costs and waste", "transparen",
                   "anticipate and act before issues or challenges arise", "reacting to them after they occur",
                   "adapt to schedule and product changes with minimal intervention", "self-correction",
                   "greater overall asset efficiency",
                   " predict and detect quality defect sooner and can help to identify causes of poor quality",
                   "a better-quality product with fewer defects and recalls", "more cost-efficient processes",
                   "labor wellness and environmental sustainability", "differentiate themselves",
                   "function more effectively and efficiently"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5058", 1,
                  ["inventory tracking", "production downtime", "optimization decision", "supply chain",
                   "operational technology", "real-time decision", "smart sensor", "data visualization",
                   "asset efficiency", "scrap rate"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5059", 1,
                  ["take on", "translate into", "react to", "tap into", "adapt to"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5060", 2,
                  ["智能工厂代表着从更传统的自动化向完全互联且灵活的系统的飞跃，该系统可以使用来自互联运营和生产系统的源源不断的数据来学习和适应新的需求。",
                   "历史上，由机器做出“决定”的情况是基于自动化和线性的，例如打开阀门或根据一套明确的规则打开和关闭泵。",
                   "整合来自运营和业务系统以及供应商和客户的数据，就能够全面了解上下游供应链流程，从而提高整体供应网络效率。",
                   "智能工厂基于历史数据和实时数据预测未来结果的能力可以提高正常运行时间、产量和质量，并能预防安全问题。",
                   "然而，在智能工厂环境中，人类工作者的角色可能会具有更高的判断力和现场裁量权，从而提高工作满意度并减少人员流动。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5061", 2, [
            " The smart factory is a fully connected and flexible system that can integrate data from connected operations and production systems to self-optimize performance, self-adapt to new demands, and autonomously run entire production processes."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5063", 1,
                  ["C", "B", "E", "D", "A"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5064", 0,
                   ["B", "C", "C", "D", "B"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5065", 1,
                   ["claims", "manufacture rockets",
                    "produce about 95 percent of the rocket through automated 3D printing",
                    "engine injector and chamber", "needed by conventional rocket assembly processes.",
                    "10-story-tall launcher", "delivering payloads up to 2,755 pounds",
                    "a compact car—into low Earth orbit", "low Earth orbit"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5068", 1, ["简而言之",
                                                                                                    "So in a nutshell, innovation, higher productivity, fewer old jobs, and many new and often better jobs. ",
                                                                                                    "迅速发展",
                                                                                                    "While new information age industries are booming, they are creating fewer and fewer new jobs.",
                                                                                                    "失去势头，失去动力",
                                                                                                    "Old innovative industries are running out of steam. ",
                                                                                                    "势头，推进力",
                                                                                                    "Decades of investment kept this momentum going. ",
                                                                                                    "与……同等",
                                                                                                    "Some technologists argue that the Internet is an innovation on a par with the introduction of electricity.",
                                                                                                    "等同于",
                                                                                                    "Innovation in the information age doesn’t equate to the creation of enough new jobs, which would be bad enough on its own, but now a new wave of automation and a new generation of machines is slowly taking over.",
                                                                                                    "边缘",
                                                                                                    "Machines are on the brink of becoming so good at breaking down complex jobs into many predictable ones, that for a lot of people, there will be no further room to specialize.",
                                                                                                    "即将",
                                                                                                    "We are on the verge of being out-competed.",
                                                                                                    "被打败，被淘汰",
                                                                                                    "We are on the verge of being out-competed."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5071", 2, [
            "set the scan options.You can use buttons on the scanner to select among several scanning options.position the photo on the scanner.1 Place the photo face down on the scanner glass. The top of the photo should be toward the back and left side of the scanner.2 Slide the photo within the border markings on the scanner glass.3 Close the scanner lid.Note: To find out about positioning large photos or documents, see scan photos larger than 10 x 15 cm (4 x 6 inches) on page 25.change the image qualityThe scanner has three image quality settings for photos: Good, Better, and Best. It also has a Text setting for scanning text documents. On the front panel display you can view the current quality setting.to change the image quality:Press the Quality button until the setting you want appears on the front panel display.The settings change incrementally from Good, to Better, to Best, then to Text. The quality setting determines the quality of the images and how many images you can store on the memory card.When you change the quality setting, the scanner will recalculate the number of photos remaining. If the quality is changed to a level beyond the amount of memory remaining, the number of photos remaining will be zero and the scanner will not scan.For information on how the quality setting affects the number of images that fit on the memory card, see memory card capacity on page 38."]]

    }

    unit_7 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5081", 0,
                  ["B", "D", "A", "C", "C"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5082", 1,
                  ["H", "D", "E", "C", "F", "A", "G", "B"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5087", 1,
                  ["exercise of geopolitical power around the distribution of those resources",
                   "economic advantages for those countries that extracted those resources",
                   "some degree of energy independence in the new energy system for almost every country",
                   "a profound impact on the global economy and potential to reshape the geopolitical landscape",
                   "the United Arab Emirates ", "Saudi Arabia", "to adopt a new, diversified, economic model",
                   "Nigeria", " Angola", " Gabon", "unprepared", "energy players",
                   "The majority of renewables capacity addition", "Morocco ", "Chile", " hydrocarbon reserves",
                   "all strategies to combating climate change",
                   "mitigate against wider socio-economic stresses and shocks", "Potentially severe social disruption",
                   "a cross-understanding of industrial policy and social policy"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5088", 1,
                  ["energy transition/transformation", "fossil fuel", "biomass energy", "clean energy power generation",
                   "emerging economies", "capacity addition", "electricity mix", "hydrocarbon reserves",
                   "energy-fuelled conflicts", "coal industry/sector"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5089", 1,
                  ["call for", "pose a threat to", "in place", "as such", "play out"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5090", 2,
                  ["能源转型所带来的最大挑战之一是，化石燃料生产国——其中许多是过去依靠这些资源发展经济的国家——要采取一种新的多样化的经济模式。",
                   "如果你想到快速的能源转型对化石燃料资源价格的影响，以及它可能对尼日利亚、安哥拉、加蓬和其他高度依赖这些资源的国家的影响，那么除非这些国家有雄心勃勃的经济多样化战略，否则它们在不久的将来可能会面临一些严峻的挑战。",
                   "在这一领域，有一些国家处于领先地位，比如摩洛哥，该国正从90%的能源进口依赖转向到2030年可再生能源在其电力结构中占52%的目标——这是一个非凡的成就。",
                   "可再生能源还有额外的潜力，即通过改善10亿能源贫困人口的能源供应，通过创造就业机会、减少当地污染、促进可持续发展和减轻对稀缺自然资源的竞争，可以缓解更广泛的社会经济压力和冲击，这些压力和冲击也可能导致冲突。",
                   "但是，如果你想一想技术如何开始重塑全球经济，如果我们迅速进入基于可再生能源的经济电气化——在这个经济体中，像交通这样的主要部门变得越来越电气化——那么你可以看到在全球雇佣数百万人、拥有数千亿美元投资的整个传统汽车供应链很快就开始面临重大挑战。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5091", 2, [
            " The world is shifting from an energy system based on fossil fuels to one based on renewable energy. Director-General of the International Renewable Energy Agency, Adnan Z. Amin, talks about how this transition is set to disrupt the geopolitical landscape."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5093", 1,
                  ["B", "A", "C", "E", "D"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5094", 0,
                   ["B", "C", "B", "A", "D"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5095", 1,
                   ["that they can go well beyond the blackbody limit and produce more energy",
                    "that uses two silicon surfaces very close together", "vacuum",
                    "one surface and cooled another surface", " heat flux", " generate ",
                    "improve the efficiency of solar panels", " automobiles ",
                    " take the heat from the engine to help power the electrical systems"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5098", 1,
                   ["另一方面", "On the flip side, we have abundant sun, water, and wind", "（炼铁的）高炉，鼓风炉",
                    "Electricity powers blast furnaces, elevators, computers, and all manner of things in homes, businesses, and manufacturing",
                    "千万亿",
                    "The sun continuously radiates about 173 quadrillion watts of solar energy at the earth, which is almost 10,000 times our present needs",
                    "地热的",
                    "There are other forms of renewable energy we could draw from such as hydroelectric, geothermal, and biomasses, but they also have limits based on availability and location",
                    "极高的，天文数字的", "But building a system on this scale faces an astronomical price tag", "消耗",
                    "Present-day power lines lose about 6 to 8% of the energy they carry because wire material dissipates energy through resistance",
                    "锂离子电池",
                    "Recently, we’ve gotten better at producing lithium-ion batteries, which are lightweight and have high energy density",
                    "兆焦（耳）", "But even the best of these store about 2.5 megajoules per kilogram", "多方面的",
                    "Priorities on how to tackle this challenge depend on the specific assumptions we have to make when trying to solve such a multifaceted problem, but there’s ample reason to be optimistic that we’ll get there."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5101", 0,
                   ["C", "A", "C", "D", "D", "B"]]

    }

    unit_8 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5110", 0,
                  ["D", "B", "C", "D", "C"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5111", 1,
                  ["F", "E", "H", "B", "G", "D", "C", "A"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5116", 1, [
            "the lifeblood of modern cities, a critical economic factor, and a facilitator of smart, sustainable development",
            "urban mobility challenges and examples of smart city solutions",
            " safe, clean, reliable, and affordable transport", " reduce and control pollution levels",
            "inevitable traffic congestion, emissions and safety problems", "public transport ridership",
            "urban population density", " vulnerable road users", "Greater reliance on digital technologies",
            " limited mobility options", "transport poverty", "Moovel", "TimesUpp", "PSIroads", "Parquery",
            " eCooltra", " the city of Lublin", "the HiReach project",
            "affordable, multimodal, on-demand mobility options", "shared electric and autonomous vehicles",
            " the elimination of road fatalities", "improvement in travel times", " reduction of air pollution"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5117", 1,
                  ["urban mobility solutions", "capacity of road infrastructure", "disruptive business models",
                   "public transport ridership", "transit stops", "vulnerable road users", "on-demand service",
                   "electronic displays", "ridesharing", "autonomous vehicles"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5118", 1,
                  ["collide with", "perspective on", "equivalent to", "committed to", "deny access to"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5119", 2,
                  ["尽管城市认识到公共交通有助于减少污染和拥堵，但地方政府提供这些好处的努力可能会与优步和其他叫车服务等颠覆性的商业模式发生冲突。",
                   "根据利兹大学的研究，出现以下情形而使人们不能满足其基本活动需求时，其会遭受交通匮乏之苦。这些情形涉及交通工具的出行时间、可得性、可达性，以及交通选择的可负担性和充分性。",
                   "用户超过15万人的TimesUpp“将用户的日历变成完美的旅行助手，提供到达目的地的最佳时间和交通方式的建议，实时更新交通堵塞和其他意外延误信息。”",
                   "从城市交通的创新趋势和颠覆性力量来看，下述对未来情景的设想是现实的：智能城市居民和游客享受更广泛的可负担得起的、多模式的、按需的交通选择；传统的汽车和所有权被共享电动车辆和自动驾驶车辆所取代。",
                   "波士顿咨询集团认为，自动驾驶技术的广泛应用将带来巨大的好处——可以消除道路死亡人数，将出行时间缩短40%，弥补通勤和交通拥堵造成的数十亿小时的损失，并为社会带来价值1.3万亿美元的总效益。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5120", 2, [
            " Mobility is an important element in smart city planning. According to McKinsey, there are quite a few urban mobility problems in all major cities in Europe—pollution, traffic congestion, increasing road fatalities, cybersecurity risks, citizens with limited mobility options and in “transport poverty”, just to name a few.Fortunately, various solutions have sprung up. In such fields as mobility as a service, sustainable travel behavior, traffic management, traffic congestion and micromobility management, European companies design and launch state-of-the-art products to help improve mobility with the latest advance in technologies. Through innovative efforts the city of Lublin in Poland was recognized as “Smart City of the Year 2015 with population between 100, 000 and 350,000” for investments in the traffic management system and solutions in collective transport. The HiReach project funded under Europe’s Horizon 2020 program is committed to the reduction of transport poverty.All these promise a future when residents and visitors enjoy a wider range of affordable, multimodal, on-demand mobility options and the benefits brought by the elimination of road fatalities, improvement in travel times and reduction of air pollution."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5122", 1,
                  ["B", "E", "D", "A", "C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5123", 0,
                   ["C", "B", "D", "A", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5124", 1,
                   ["feature a plethora of technology",
                    "sleek infotainment systems, side opening doors, stylish interiors and unique safety features.",
                    "the speeds they travel and how long electric batteries currently last.", " evolved",
                    "offering up features we so far can only dream of"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5128", 1, ["沥青",
                                                                                                    "While road types can vary greatly depending on their use, location, and the construction method, the majority are formed from crushed rock, sand, and asphalt, in a process that releases volatile organic compounds into the atmosphere.",
                                                                                                    "挥发性有机化合物",
                                                                                                    "While road types can vary greatly depending on their use, location, and the construction method, the majority are formed from crushed rock, sand, and asphalt, in a process that releases volatile organic compounds into the atmosphere. ",
                                                                                                    "控制，抑制",
                                                                                                    "In order to curb the environmental impacts of road construction, a number of new innovations are now being trialed.",
                                                                                                    "路面坑洞",
                                                                                                    "In India, the process of melting plastics to filling potholes has been happening on a small scale for a number of years.",
                                                                                                    "颗粒，球丸",
                                                                                                    "British engineer, Toby McCartney, recognized the benefits of using plastic in roads while traveling the country, and developed a method of turning plastic bottles into small pellets that could be added to an asphalt mix to increase its bulk.",
                                                                                                    "预制的",
                                                                                                    "Taking things a step further, Dutch company KWS, together with Wavin, and Total have developed PlasticRoad, a prefabricated modular roadway made from recycled plastic.",
                                                                                                    "硅石，二氧化硅",
                                                                                                    "While the concept may sound advantageous, critics have raised a number of concerns around this new type of roadway, including the safety of vehicles driving over the toughened glass or silica that is required to protect the photovoltaic elements and how effective horizontal solar panels can be as compared to those positioned diagonally on roofs. ",
                                                                                                    "光伏，光电的",
                                                                                                    "While the concept may sound advantageous, critics have raised a number of concerns around this new type of roadway, including the safety of vehicles driving over the toughened glass or silica that is required to protect the photovoltaic elements and how effective horizontal solar panels can be as compared to those positioned diagonally on roofs. ",
                                                                                                    "试验性的",
                                                                                                    "Several pilot schemes are now underway, seeking to overcome these challenges. "]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5131", 2, [
            "摘要在基于稳态视觉诱发电位（SSVEP）的脑机接口（BCI）中，有效的频率识别算法至关重要。在本研究中，我们提出了一个分层特征融合框架，可用于设计高性能的频率识别方法。该框架包括空间维数（SD）融合和频率维数（FD）融合两种融合技术。采用带非线性函数的加权策略，得到了SD和FD融合。为了评估我们的新方法， 我们使用了相关成分分析（CORRCA）方法来研究提出的框架的效率和有效性。实验结果来自于35个受试者的基准数据集，表明框架内使用的扩展CORRCA方法显著优于原CORCCA方法。因此，该框架有望提高基于SSVEP的BCI中频率识别方法的性能。"]]

    }

    unit_9 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5141", 0,
                  ["D", "C", "C", "C", "A"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5142", 1,
                  ["H", "D", "G", "F", "B", "C", "E", "A"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5147", 1,
                  ["logic", "hard-wired", "drop ", "compress ", "notations ", "sorting", "computation", " features",
                   "advantages", "big data", "machine-learning system", "optimize all parameters", "designers"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5148", 1,
                  ["design and fabrication", "computational tools", "post-human logic", "data-compression technology",
                   "physical shape", "material property", "robotic arms", "micro-designing", "metaphysical implication",
                   "industrial revolution"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5149", 1,
                  ["in the business of", "at play", "to the contrary", "on the fly", "deal with"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5150", 2,
                  ["二十年前，我们认为计算机是制造产品的机器。而今天，我们发现计算机作为思维工具，更加不可或缺。",
                   "将字母排序作为我们一般思维方式的隐喻：我们将物品放在特定的地方，这样在我们需要时就知道它们在哪里；我们也对事物和思想进行分类以了解世界。",
                   "没有任何一个现代工程师或承包商会想象逐一记录每块砖，因为那可能需要花一辈子的时间，而且由此产生的施工文件会像印刷出版的《大英百科全书》一样厚。",
                   "将建筑物的每一个微小颗粒以可用的最小比例进行微观设计，可以节省大量的建筑材料、能源、劳动力和金钱，并使交付的建筑物更加符合规范要求。",
                   "但是，正如20世纪的工业设计面临机械制造方式的挑战一样，21世纪的后工业设计需要应对计算机思维方式的挑战。因为正如由工业革命产生的机械机器违背了人体的有机逻辑，当今的思维机器（计算机）与人类思维的有机逻辑相悖。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5151", 2, [
            " Designers have been using computer-based tools for design and fabrication for many years. With the power of computing tools, computers have become more than just manufacturing tools, but have evolved into indispensable thinking tools. With their unique logic, computers can solve more and more human problems. The main difference between the way we think and the way computers solve problems is that our brain was never hard-wired for big data. When dealing with too many facts and data, we have to compress them into shorter notations or adopt the method of classification. It may lead to the loss of information in the process. Compared with humans, computers are superior in computation and data processing and they can search without sorting. Because of these properties, in the field of architecture, computers can notate every brick of a building and micro-design each minute particle of a building, which may save plenty of building material, energy, labor and money and can deliver buildings that are better fit to spec. Although computers have advantages over humans in big data, no machine-learning system can optimize all parameters of a design process in the meantime, only designers can. Coping with computer’s way of thinking will be the challenge of postindustrial design, but fears of competition coming from Artificial Intelligence may be unnecessary."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5153", 1,
                  ["C", "D", "E", "B", "A"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5154", 0,
                   ["D", "A", "D", "B", "B"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5155", 1,
                   ["high, strong walls", "towers and battlements of all necessary and pleasant beauty",
                    "the sublimity and magnificence of a holy temple", "the convenient composition of private homes",
                    "upper layers of the city", "undisturbed", "services, trade, transport and industry", "width",
                    " the average height of the adjacent houses", "many contemporary cities across Italy",
                    "allow access to sun and reduce the risk of damage from earthquakes"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5158", 1, ["受电弓",
                                                                                                    "Owls inspired the pantograph, that’s the rig that connects the train to the electric wires above. ",
                                                                                                    "锯齿状和弯曲的形态",
                                                                                                    "Nakatsu modeled the redesign after their feathers, reducing noise by using the same serrations and curvature that allow them to silently swoop down to catch prey. ",
                                                                                                    "向下猛冲",
                                                                                                    "Nakatsu modeled the redesign after their feathers, reducing noise by using the same serrations and curvature that allow them to silently swoop down to catch prey.",
                                                                                                    "轴",
                                                                                                    "The Adélie penguin whose smooth body allows it to swim and slide effortlessly inspired the pantograph supporting shaft redesigned for lower wind resistance.",
                                                                                                    "分贝",
                                                                                                    "When the redesign debuted in 1997, it was 10% faster, used 15% less electricity, and stayed under the 70-decibel noise limit in residential areas. ",
                                                                                                    "仿生学",
                                                                                                    "There’s a name for design like this, it’s called biomimicry.",
                                                                                                    "壁虎",
                                                                                                    "Stick like a gecko, compute like a cell, even run a business like a redwood forest. ",
                                                                                                    "洞穴",
                                                                                                    "That might mean studying prairie dog burrows to build better air ventilation systems, mimicking shark skin to create bacteria-resistant plastic surfaces for hospitals, or arranging wind turbines in the same drag-reducing pattern that schools of fish swim in. ",
                                                                                                    "流行词",
                                                                                                    "There’s a buzzword right now that’s really hot, called the circular economy, which is essentially, you know, industry saying, you know, there should be no such thing as a byproduct in our manufacturing facility that goes to landfill, it should be used by something else, right, and at the end of a product’s life, that product should be up-cycled into something else, it’s being called the circular economy."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5160", 1,
                   ["C", "B", "D", "N", "F", "I", "A", "H", "J", "L", "E", "K", "M", "G", "O"]]

    }

    unit_10 = {
        "task2": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5169", 0,
                  ["C", "A", "B", "D", "C"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5170", 1,
                  ["F", "A", "G", "C", "B", "D", "E", "H"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5175", 1, [
            "Smart cities offer its habitants the comforts of metropolitan living combined with the benefits of rural life",
            "Smart buildings help cities build data ecosystem, which improves the efficiency of city infrastructures.",
            "Every building can be high-performance energy supplies.",
            "Holographic studio allows people to meet and eat in virtual space.",
            "Self-service system can be used everywhere."]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5176", 1,
                  ["digital technology", "smart building", "data ecosystem", "automation and visualization system",
                   "neuronal networks", "urban infrastructure", "wind generator", "solar panel", "holographic studio",
                   "virtual space"]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5177", 1,
                  ["be in line with", "in tandem with", "toy with", "take over", "in advance of"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5178", 2,
                  ["数字技术的发展提高了城市基础设施的效率，同时使越来越多的人可以在家完成大部分工作，未来的智能城市将为居民提供兼具乡村好处与大都市便捷的生活方式。",
                   "它坚持可持续性发展和区域主义的原则，致力于创造可供所有人自由进入的功能性社会组织与公共空间",
                   "现在，所有这些信息构成了一个能够自我管理的虚拟数字生态系统。该系统是基于神经元网络的学习系统，能够筛选海量数据生成智能信息，自主提高城市基础设施效率。",
                   "由此产生的精确匹配能源需求与供给的能力，大大降低了城市的成本。", "尽管这从根本上减少了城市的排放量，但人们也因此变得越来越孤独和不快乐——全息工作室的需求由此产生。"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5179", 2, [
            "Thanks to digital technologies, the smart cities of the future offer their inhabitants the comforts of metropolitan living combined with the benefits of rural life and returning to cities has been an option of people who once moved to the countryside. What changes have taken place in urban life? First of all, in big cities, smart buildings become a norm. Each building is networked to the eaves and embedded within City Intelligent Platforms, which are used to process vast volumes of data from sensor networks. All the information constitutes a virtual digital ecosystem that administers itself. Meanwhile, the building has become a high-performance energy supplier. People can store energy from the solar panels on the fa?ade and wind generators on the roof. As global networking expanded, people could do almost everything at home. While this reduces emissions, it makes people lonely and unhappy. The advent of holographic studio solves the problem. It helps people to meet and eat in the virtual space. In addition, self-service system is everywhere. For example, when the ingredients for a cake in the bakery are out of stock, the autonomous supply vehicle can fill up itself without receiving instructions. All in all, the development of science and technology, along with the popularity of the Internet have made life convenient in many ways and improve people’s quality of life."]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5181", 1,
                  ["C", "A", "E", "B", "D"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=5182", 0,
                   ["A", "C", "C", "D", "B"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5183", 1,
                   ["integrated", "advanced IoT sensors", "keep a check on moisture levels and plant health",
                    "intervene", "sensors, cameras and sprayers ", "identify the pests and application of pesticides",
                    "nascent",
                    "establish the field and boundary maps, define operating conditions and program the best field paths using the path planning software"]],
        "task13": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=5186", 1, ["道德规范",
                                                                                                    "Certainly, as it relates to our technical engineering profession, we can understand our code of ethics, what the obligation is of our society that society has for engineers and also being sure to hold paramount the safety health and welfare of the public. ",
                                                                                                    "最重要的",
                                                                                                    "Certainly, as it relates to our technical engineering profession, we can understand our code of ethics, what the obligation is of our society that society has for engineers and also being sure to hold paramount the safety health and welfare of the public.",
                                                                                                    "困境",
                                                                                                    "There’s a number of different ethical dilemmas that come up for newer professionals.",
                                                                                                    "可计费的",
                                                                                                    "It’s common to hear a situation where a new professional is pressured to put billable hours on a project that they didn’t necessarily directly work on.",
                                                                                                    "内部资金",
                                                                                                    "Some cultures in business really have no in-house fund to charge hours to and that all of the hours from an engineer needs to be billable to a project. ",
                                                                                                    "坚定的",
                                                                                                    "Certainly, some engineers feel quite adamant that billing hours to a project that they didn’t work on is not a truthful statement. ",
                                                                                                    "住房抵押贷款",
                                                                                                    "One mid-career engineer said that he really needed to pay his home mortgage, he had a family to support, he would do anything that the client or a supervisor asked him to do without question.",
                                                                                                    "产生共鸣",
                                                                                                    "I hope it resonated with other people in the room.",
                                                                                                    "揭发",
                                                                                                    "So, if necessary, the engineer has to blow the whistle?"]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=5188", 2, [
            "我要特别感谢下面这些人，他们使我的研究取得了成功，并在各个方面帮助我坚持我的目标：我的导师米尔恩博士，感谢他的大力支持和帮助，他的鼓励使实现目标成为可能。我的导师助理威尔逊博士，在我研究的每一个阶段，他的帮助和富有同情心的态度帮助我及时进行工作。化学系主任本森教授，他的提醒和不断的动力鼓励我按时完成任务。化学系的全体教职员工和实验室技术人员，他们的服务使我的研究获得了成功。我的父母、家人和朋友，没有他们，我什么都不是；他们不仅在经济上帮助我，而且在道义上和情感上也给予了我支持。",
            "The research was supported by the National Science Foundation under Grant No. 1678326. We would like to show gratitude to colleagues at the University of California Irving who provided insights and expertise that greatly assisted the research. We thank Professor Jose Cruz of the Ohio State University for comments that greatly improved the manuscript. We would also like to thank Tony Spencer for his assistance in collecting the data."]]

    }
