class Answer_All():
    unit_1 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4617", 1,
                  ["permutation", "confine", "accumulation", "bacteria", "diagnostic", "denote", "commodity", "thesis",
                   "discipline", "apparatus", "sensitivity", "onset", "workshop", "valve", "inversion", "graph",
                   "variance", "layout", "dynamic", "transparency", "fringe", "orientation", "accumulate", "molecule",
                   "gradient", "occurrence ", "incumbent ", "ion", "stabilize", "irrigation", "partition",
                   "quantitative", "generalization ", "fabric ", "circa", "processor", "drain ", "plantation",
                   "sediment", "transcribe", "lateral", "proposition", "cognitive", "equilibrium", "quantum",
                   "scenario", "transmit", "footnote", "generator", "presume"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4618", 1,
                  ["equilibrium", "discipline", "fringe", "quantum", "graph", "molecule", "generator", "apparatus",
                   "valve", "gradient"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4619", 1,
                  ["denote", "variance", "accumulation", "layout", "confined", "transmit", "onset", "cognitive",
                   "sediment", "diagnostic"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4620", 1,
                  ["endeavor", "knowledge ", "figure out", "paved the way", "problem solvers ",
                   "the analysis of a problem", "the creation of a solution", "interact with", "collaboration",
                   "fact checking"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4621", 2,
                  ["Electrical engineering, civil engineering, mechanical engineering and chemical engineering.",
                   "The qualities of being practical, analytical, logical; of thinking outside the box; of being curious, interested in problem-solving and creative."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4623", 2,
                  ["Dujiangyan", "over 2000 years", "LI Bing",
                   "regulating the flow of the Min River to prevent floods and provide consistent irrigation for farming",
                   "diverting part of the Min River at Dujiangyan"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4624", 1,
                  ["allowed production on an industrial scale", "detecting earthquakes", "bored for natural gas",
                   "the passage of the planets and the stars", "forging metal"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4625", 1,
                  ["craft", "C", "simulation", "H", "aeronautical", "F", "status quo", "A", "epistemology", " E",
                   "scale model", "I", "construe", "B", "stipulation", "D", "prototype", "J", "filter", "G"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4626", 0, ["B"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4627", 0, ["C", "D", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4628", 2, [
            "The main job of an engineer is to recognize, comprehend and construe the limitations on a particular design to get successful results.",
            "Problem solving: understanding of mathematics, logic, science and economics and proper experience is used tactfully by the engineers to solve potential problems.",
            "Engineers normally try to foresee how their designs will perform to their specifications before it can be produced on a larger scale."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4633", 1,
                   ["assembly line", "manufacturing facilities", "electrical technology", "automated production",
                    "renewable energy", "programmable logic controller ", "machine learning", "the Internet of Things",
                    "cyber-physical system ", "cloud computing"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4634", 1,
                   ["mechanization of steam and water power",
                    " various management programs that perfected the effectiveness of manufacturing facilities ",
                    "Internet access, connectivity and renewable energy ", "steam and water power", "electrical power",
                    "programmable logic controllers", "smart machine, storage systems, production facilities ",
                    "the Internet of Things",
                    "a level of digital intelligence to devices (enabling them to communicate without a human being involved and merging the digital and physical worlds)",
                    "cyber-physical systems",
                    "link the physical world with the virtual world of information processing", "cloud computing ",
                    "users are able to access software and applications from wherever they are ",
                    "cognitive computing ", "simulate human thought processes in a computerized model"]]
    }

    unit_2 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4640", 1,
                  ["receptor", "adjacent", "diameter", "millimeter", "fracture", "inference", "transplant ",
                   "thickness", "modular", "bubble", "reconstruct ", "entrant", "detection", "decentralize",
                   "deflection", "integral", "approximate", "artifact", "alien", "magnitude", "gauge", "instability",
                   "consent", "generalize", "alert", "oxidize", "allocate", "insert", "approximation", "fossil",
                   "practitioner", "randomize", "vector ", "thereby", "manual", "quotation", "bulk", "economist",
                   "deadline", "membrane", "indigenous", "unstable", "contradiction", "slab", "epidemic", "acidic",
                   "utility ", "pulse", "genetics", "identical"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4641", 1,
                  ["slab", "gauge", "magnitude", "millimeter ", "modular", "receptor", "diameter", "oxidize", "manual",
                   "decentralize"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4642", 1,
                  ["fossil", "deflection", "detection ", "utility", "allocate", "membrane", "bulk", "transplant",
                   "randomized ", "fracture"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4643", 1,
                  ["high-volume", "high-velocity", "high-variety", "process automation", "the relational database",
                   "online services", "Hadoop", "open-source frameworks", "easier to work with", "cheaper to store"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4644", 2,
                  ["The descriptive one, the diagnostic one, the predictive one and the prescriptive one.",
                   "It helps companies or public administrations understand their users better, find previously unnoticeable opportunities, provide a better service, and even mitigate fraud."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4646", 2,
                  ["Volume,Velocity,Variety ", "greater efficiency,fewer defects,greater profitability",
                   "Identify a problem that needs to be solved now and a person who wants to solve it;"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4647", 1,
                  ["probing the cosmos", "the radio waves emitted by objects", "a spider’s web ", "triangular panels",
                   "collects data from billions of light years away"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4648", 1,
                  ["revenue", "E", "scale up", "F", "hard drive", "B", "sync", "J", "outage", "I", "cash in", "G",
                   "server ", "A", "back up", "C", "account for ", "H", "access ", "D"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4649", 0, ["B"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4650", 0, ["C", "C", "A"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4651", 2,
               ["The cloud is a global network of servers around the world acting as one massive hard drive.",
                "Before the cloud, you might have backed up your documents, photos and music to an external device like a CD-ROM or to your computer's hard drive.",
                "You can access your data anytime anywhere if you're connected to the Internet and you don't have to worry about using up all of your storage on your hard drive."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4654", 1,
               ["load", "solar panel", "turbine", "disruptive ", "node ", "interoperability", "databus", "optimize",
                "heterogeneous system ", " leverage"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4656", 1,
               ["they want to ensure sufficient power to compensate for the fluctuations ", "operate on update cycles",
                "interoperable, resilient, scalable, and secure",
                "enable the efficient use of renewable energy resources at a large scale ",
                "machine-to-machine, machine-to-control center, and machine-to-cloud data connectivity",
                "devices and intelligent nodes", "with the central station and the cloud", "optimally (by taking advantage of both local and remote state)"]]

    }
    unit_3 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4658", 1,
                  ["oxygen ", "rack", "regression", "conceive", "damp", "scalable", "nominal", "infinite", "thermal",
                   "terminal", "strand ", "watershed", "cone ", "conduction ", "amplitude", "maximize", "contradict",
                   "proprietary ", "classification", "fraction", " clip", "elevate", "configuration", "fetal ",
                   "incidence", "residue", "acid", "paradox", "industrialize", "specification", "liter", "manipulate ",
                   "velocity", "versatile", " nucleus", "hierarchy", "deficiency", "optical", "audio ", "spray",
                   "discourse", "solvent", "exponential ", " autonomy ", "likelihood", "chromosome", "displacement",
                   " mechanic", "organism", " helix"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4659", 1,
                  ["velocity", " scalable ", "proprietary", "versatile ", "helix", "audio ", "regression", "cone",
                   "nucleus", "thermal"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4660", 1,
                  ["exponential", "industrialize", "conduction ", " mechanics", "fraction", " chromosomes",
                   "manipulate", "nominal", "likelihood ", "configurations"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4662", 1,
                  ["reality emulation", "believable", "interactive", "computer-generated",
                   "realistic 3D computer graphics", "in real-time", "explorable", "big and detailed enough",
                   "immersive", "engage both your body and your mind"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4663", 2, [
            "AR is based on the technology of VR. First, they both offer users good virtual experience: People can interact with visuals, and in AR and VR places are navigable; second, both of them are pretty green and have a long way to go before they hopefully merge into a smooth continuum of abilities.",
            "AR is when you look at the real world, it's augmented with additional and unreal information or graphics in your view, while VR is that the world you're standing in is replaced with a virtual one: Everything you see and hear is replaced with something computer-generated. Furthermore, AR can be had via a phone and one of the many AR apps out there, while VR is experienced with a headset, which is quite cumbersome."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4672", 2, [
            "Full immersion into virtual simulation;No risks to real equipment and health;No limits to simulation scenarios;Lower training costs by 10-20 times;Multi-user simulations;Augmented reality helmets for in-field work.",
            "AR information in real-time;Supervising."]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4673", 1,
                  ["pave the way for cutting-edge advances", "a virtual reality headset and a special glove",
                   "the wide adoption of a new generation of self-driving cars",
                   "an enhanced VR experience that includes the sense of touch", "revolutionize many industries"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4674", 1,
                  ["shrink", "E", "tilted", "F", "graphics", "A", "prototype", "I", "filtered", "G", "motion-tracked",
                   "C", "contact lenses", "J", "avatar", "H", "console", "B", "trauma", "D"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4675", 0, ["C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4676", 0, ["B", "D", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4677", 2, [
            "There have been many experiments with virtual reality and augmented graphics in every decade since the 1960s.",
            "Kauffold says that lessons using VR immersion could be more engaging, rid the classroom of distractions, and give teachers further control of their students.",
            "Even though the future of VR and augmentation could be both dark and bright, all we can do is hope that we don’t end up as the lead role in our own personal episode of Black Mirror."]],

        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4680", 1,
               ["circuit", "chip", "central processing unit ", "memory ", "binary ", "execute", " sequence",
                "rectangle", "the operating system", " fraction"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4683", 1,
                       ["hardware", "software", "circuits, chips, wires, speakers, plugs", "Software ",
                        "applications, games, web pages, and the data science software ", "CPU",
                        " controls all the other parts of the computer",
                        "in binary ones and zeros or on and off electrical signals", "a very simple computer program",
                        "the most basic form of software and it controls all the hardware of a computer ",
                        "an operating system managing software",
                        "just electrical signals flowing through billions of tiny circuits"]],

    }
    unit_4 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4684", 1,
                  ["substitution ", " interactive", "terminology ", "legitimate", " clone", "comparative", "mediate",
                   "sperm", "utilize", "athletic", "virtual", "niche ", "molecular", "standardize", "neural",
                   "spontaneous", "rationality ", " ritual ", "expertise", "project", "facilitate", "analogy", "toxic",
                   "precipitation", " innate", "differential ", "soluble", "induction", " fluid", "lever", "consensus",
                   "marginal", "rhythm", "dissertation", " metabolism", "null", "yeast ", "transaction", "dissolve",
                   "longitudinal", "mobility", "criteria", "rotate ", "sophisticate", "artificial", "inhibit",
                   "discrete", "turbulent", "embed", "nonlinear"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4685", 1,
                  ["molecular", "artificial ", "interactive ", " nonlinear ", "virtual", "metabolism", "terminology",
                   " lever ", "fluid", "longitudinal"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4686", 1,
                  ["mobility", "standardize", "embed", "facilitate", "discrete", "expertise ", "soluble", "utilize ",
                   " rotate", "analogy"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4687", 1,
                  ["computing concept", "identify themselves to other devices", "real-world applications",
                   "smart homes", "computers, smartphones or other mobile devices", "Smart buildings", "sensors",
                   "adjust automatically", " alleviate traffic", "improve sanitation"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4688", 2, ["Security risks.",
                                                                                                  "Security vulnerabilities in the IoT devices can be exploited by hackers so that they may become uninvited guests to people's homes."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4689", 2,
                  ["China will officially begin the actual development of 6G in 2020;begin commercial use until 2030.",
                   "6G networks will be a thousand times faster than 5G; connect to all the devices people use;achieve better application in large bandwidth, low latency and wide connection.",
                   "fast download speed;greatly improved Internet of Everything;greatly improved machine-to-machine communication;high-definition video stream; impact on autonomous vehicles, Car-Internet, smart homes, remote diagnostics and remote education"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4690", 1,
                  ["people also navigated by the Big Dipper", "the world’s fourth navigation satellite system",
                   "global coverage", "that are compatible with GPS",
                   "positioning, navigation, timing and short-messaging services"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4691", 1,
                  ["brink", "E", "tsunami", "J", "optical fiber", "C", "packet switching", "D", "unison", "I", "analog",
                   "B", "consensus", "F", "sustainable", "H", "exponentially", "G", "geostationary orbit", "A"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4692", 0, ["B"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4693", 0, ["D", "C", "D"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4694", 2,
                   ["In 1964, the first communication satellite was installed in a geostationary orbit.",
                    "Optical fiber networks were installed and the transition to packet switching began-the highly efficient triple play of voice, video, and data. ",
                    "ITU standardization is working to build a human-centric ICT environment, where physical space and cyberspace are managed in unison."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4696", 1,
                   ["embed", "platform", "trigger", "brake line", "diagnostic bus", "gateway", "coupon", " warranty",
                    "pinpoint", "inventory"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4697", 1,
                   ["vehicles", "home appliances",
                    " brings us diverse information together and provides the common language for the devices and apps to communicate with each other ",
                    "by sophisticated sensors and chips ", " the physical things that surround us",
                    "whether it’s something minor or something that needs immediate attention ",
                    "being transmitted to the manufacturer’s platform ", "in a secure database", "rules and logic",
                    "an alert in the car", "create and manage applications that solve specific issues",
                    "deploy an application on the platform called the asset management system",
                    "deploy a continuous engineering application that tracks not only one person’s car, but hundreds of thousands of others, looking for ways to improve the design and manufacturing process of the car itself"]],
    }
    unit_5 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4579", 1,
                  ["monopoly", "proton", "complement", "interface", "dilute", "scatter", "circulation", "logical",
                   "constrain", "vitamin", "magnetic", "reactive", "swap", "missile", "tremendous", "mercury", "cord",
                   "replicate", "mole", "immersive", "repertoire", "antibody", "static", "conservation", "multiply",
                   "antibiotic", "simulate", "feedback", "marrow", "coordination", "articulate", "linear ", "sodium",
                   " nitrogen", "assert", "numerical", "predominantly", "potassium", "flux", " inhibition", "factorial",
                   "unintelligible", "dissection", "variant", "beam", "forum ", "correlation ", "enzyme", "dimensional",
                   "momentum"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4580", 1,
                  ["antibiotic", "momentum", "proton", "beam", "enzyme", "interface", "flux", "vitamin", "nitrogen",
                   "sodium"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4581", 1,
                  ["feedback", "reactive", "variants", "monopoly", "simulating", "correlation", "replicate", "magnetic",
                   "static", "dilute"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4583", 1,
                  ["computing hardware", "the data", "complex and powerful", "an effective conclusion",
                   "detailed algorithms", "computing tasks", "human minds", "applications", "ecosystem",
                   "it may ultimately be able to solve "]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4584", 2, [
            "Social media sites use it to create your feed based on your preferences and search engines use it to improve the accuracy of their search results. It’s also being used on a larger scale: the medical industry is applying machine learning to things like predicting life spans, organizing patient data and even diagnosing certain diseases.",
            "There is a concern that machine learning, just like many emergent technologies, may eliminate certain jobs."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4586", 2,
                  ["executing rescue missions", "3D printing ",
                   "assisting human beings to do things that you cannot do on your own (lifting heavy things, help disabled people in mobility)", "emotional intelligence",
                   "using very little power and accomplish a lot (e.g. in medical treatment)"]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4587", 1,
                  ["academics, engineers and fashionists are working together to envision the future of fashion retail",
                   "items you pick up from RFID-enabled clothing rack will automatically show up on the Mirror",
                   "add items to your virtual shopping car",
                   "Real-time analytics enable staff to move much faster and provide customers with an efficient, stress-free experience",
                   "explore more mix-and-match options from other brands"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4588", 1,
                  ["surge ", "G", "brakeman", "F", "locomotive", "E", "humanoid", "A", " cited", "B", "retrain", "J",
                   "transportation", "C", "logistics", "D", " empathy", "I", "replicate", "H"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4589", 0, ["C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4590", 0, ["D", "B", "A"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4591", 2,
                   ["There’s no denying robots and automation are increasingly part of our daily lives.",
                    "Occupations that require repetitive and predictable tasks in transportation, logistics, and administrative support were at specially high risk.",
                    "It’s hard to imagine that robots can replicate human characteristics like empathy or compassion that are required in many jobs."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4595", 1,
                   ["deep learning", "algorithm", "mimic", "weak AI", "strong AI", "unsupervised", "neural", "node",
                    "voluminous ", "subset"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4596", 1,
                   ["Artificial intelligence, machine learning and deep learning", "interpret tons of data",
                    "Artificial intelligence", "machine learning", "deep learning", "machine learning",
                    "simply any code, technique or algorithm that enables machines to mimic, develop and demonstrate human cognition or behavior ",
                    "weak AI ", "strong AI ",
                    "using techniques and processes to help machines learn the ways of humans", "supervised",
                    "unsupervised", "they demonstrate the ability to learn deeply", "an artificial neural network",
                    "the biological neural networks ", "nodes", "layers", "voluminous input data "]],

    }
    unit_6 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4706", 1,
                  ["nutrient", "accelerate", "multinational", "enforcement ", "sensible", "triangle", "elasticity",
                   "derivative", "immune", "plug", "shuttle", "projection", " urine", "radiation", "protocol", "scroll",
                   "transformation", " spatial", "degrade", " interval", "jargon", "uplift ", " notation", "binary",
                   "distribution", "photographic", "customize", "conceptual ", "reactor", "pi", "crystal", "overlap",
                   "tech ", "subtract", "flip", "diffusion", "precipitate", "duration ", " cortex", "encode",
                   "reservoir", "splice", "stadium", "ecology", " fluorescent", "outsource", "retrieve", "norm ",
                   " threshold", " flexibility"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4708", 1,
                  ["reactor", " jargon", "outsource", " triangle", "stadium", "notation", "splice", "binary ",
                   "cortex ", " fluorescent"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4709", 1,
        ["scroll", "multinational", "retrieve", "degrade", "derivative", "customizing ", "radiation", "diffusion",
         "conceptual", "encode"]],
    "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4711", 1,
              ["subtypes", "3D printing", "exciting possibilities", "taking material away", "adds to it",
               "being removed", "structures are made", "minuscule layers", "relay messages", "the desired shape"]],
    "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4712", 2,
              ["The smart factory optimizes production processes and increases efficiency.",
               "a) Augmented Reality: Augmented reality adds virtual information to the real world environment; data goggles simplify assembly tasks.b) Big Data: High-performance computers analyze vast amounts of data and identify correlations.c) Virtual Factory Plan: Production segments are planned virtually in every respect and checked using computer simulations to confirm that everything is working properly and ergonomically sound.d) Innovative Procedures: State-of-the-art 3D printers create new forms based on the ideal model of nature; with an intelligent material mix, lighter, more stable and more precise tools are built.e) Wearable Exoskeleton: Employees can perform assembly activities either seated or standing without additional physical stress or strain.f) Human-Robot Collaboration: Humans and robots work hand-in-hand on the production line.g) Driverless Transport System: Autonomous transport systems are revolutionizing logistics on the ground and in the air."]],
    "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4714", 2, [
        "creating specific engineered tissues or whole organs to match individual’s unique anatomy with no immune rejection",
        "great control in building materials and structures in 3D", "tough to deal with soft material like collagen",
        "3D print the artery made out of a gel inside a support gel made out of gelatin at room temperature;place the whole thing in the cell culture incubator at 37℃;melt the gelatin around the artery into liquid;take the 3D printed artery out."]],
    "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4715", 1,
              ["are increasingly replacing human workers with robots",
               "just investing a lot in automation and robotics", "an open attitude", "move away from low-skilled jobs",
               "redesign the production lines"]],
    "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4716", 1,
              ["apparatus", "C", "bottom line", "B", "replicate", "E", "supervisory ", "G", "inception", "A",
               "generate", "F", "realm", "J", "automated machinery", "D", "sophisticated", "I", "notify", "H"]],
    "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4717", 0, ["A"]],
    "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4718", 0, ["D", "D", "B"]],
    "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4719", 2, [
        "Automation is the automatically controlled operation of an apparatus, process, or system by mechanical or electronic devices that take the place of human labor. ",
        "Automation practically eliminates error, increases productivity and allows for better monitoring and control of the manufacturing process.",
        "As it advances even further, it is not outside the realm of possibility that one day manufacturing facilities could run without the need for humans on site at all."]],
    "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4721", 1,
               ["fused deposition modeling", "nozzle", "molten", "filament", "spool", "generic", "stereolithography",
                "resin", "selective laser sintering", "turnaround "]],
    "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4723", 1,
               ["FDM", "SLA ", "melting the raw material through a nozzle",
                "then the nozzle lays out the object layer by layer ",
                "they use a liquid resin which is hardened by a laser",
                "the material for FDM printers could be very cheap", "get much higher resolution and finer detail",
                "SLS", " too expensive",
                "great for learning about 3D printing, experimenting with different types of filaments, rapid prototyping, and more affordable ",
                "if you want to print a lot of detail in the model or need the model to come out of the printer looking shiny and smooth ",
                " a better fit for your needs"]],

    }
    unit_7 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4729", 1,
                  ["optimal", "paradigm", "methodology", " breakdown ", "productivity", "memorize", "parameter",
                   "renewable", "ethics", "bacterial", "invert", "erase", "motif ", "elevation", "portfolio",
                   "peripheral ", "friction", "aerosol", "facet", "resemble", "trivial", "aesthetic", "discharge",
                   "particle", " problematic", "preliminary", "carrier", "reinforce", "infrastructure", "magnitude",
                   "formulation", "grid", "anthropology", "archaeology", "variability", "monetary", "empirical",
                   "outlet", "phosphate", " ethical", "residual", "stack", "inject ", "connector", " mentor", "dioxide",
                   "meter", "prevalence", " synthetic ", " fungus"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4731", 1,
                  ["grid ", "meter ", "outlet", "motif", "paradigm", "empirical ", "infrastructure", "dioxide",
                   "particle", " archaeology"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4732", 1,
                  ["infrastructure", "aesthetic", "parameters", "optimal", "discharge", "breakdown", "ethical",
                   "synthetic", "peripheral", " renewable"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4734", 1,
                  ["energy sources", "converted", " electricity and hydrogen", "petroleum", " crude oil", "uranium",
                   "their supplies are limited", "the remains of plants", "geothermal energy",
                   "they are naturally replenished"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4736", 2, [
            "Fossil fuels cost more than people pay at the pump and impact our environments in many ways like global warming, air quality deterioration, oil spills and acid rain. It's also predicted that fossil fuel resources, a one-time-resource in the human timescale, will be depleted within the next 50-100 years.",
            "As for renewable energy coming from resources which naturally replenish in our lifetime, the biggest advantages are that people don't need to compromise the planet to harness it nor do they have to rely on other nations for resources, which history has shown to be a contributor to war, famine and political instability."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4738", 2, [
            "no pollution/helping with the problem of global warming, going to areas where electric trains can't go",
            " Hydrogen trains are more expensive than diesel ones.",
            "Hydrogen cells use an electrochemical process to make power-taking in hydrogen and mixing it with oxygen from the air to produce electricity."]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4739", 1,
                  ["wind, solar and hydroelectric power", "coal-fired power plants", "cap carbon emissions",
                   "giving enterprises a limit on allowable emissions", " maintenance of economic growth"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4740", 1,
                  ["crude oil", "H", "shale drilling", "I", "turmoil", "A", "scenario ", "B", "obituary", "D",
                   "back off", "G", "pump", "J", "guzzling", "C", " aviation", "F", "petrochemicals", "E"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4741", 0, ["C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4742", 0, ["D", "B", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4743", 2,
                   ["One scenario has oil peaking in the mid-2020s and the other shows oil demand growing until 2040.",
                    "Experts say it’ll be a long time before the infrastructure is in place for electric cars to overtake the streets and even then, there will still be demand for oil.",
                    "Big oil companies like Shell and BP have responded to low oil prices and increased regulations by trying to diversify their businesses."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4747", 1,
                   ["turbine", "blade", "kinetic energy", "hub", "couple", "shaft ", "gearbox", "revolution",
                    "converter ", " voltage"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4748", 1,
                   ["A wind vane at the top ", "The blades", "60 meters each", "very light and resistant materials",
                    "move easily ", "the hub which is coupled to the low-speed shaft ", "The gearbox",
                    " the low-speed shaft", "high-speed shaft", "increase the rotational speed", "a generator",
                    "converts the kinetic energy into electricity", "transforms it into alternating current (which is the most commonly used kind)", "raises the voltage ", " the substation ",
                    "underground cables", "feed it into the power grid"]],

    }
    unit_8 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4751", 1,
                  ["swell", " precede", "vertical ", "orient", "fusion", "audit", " circulate", "chemotherapy", " par",
                   "stimulus", "prey", "tribe", " closure", "congruent ", "periodic", "likewise", "stance", "pesticide",
                   "psychiatric ", "convergence", "statistics", "bracket", "manuscript", " spectrum", "render",
                   "controversy", "gravity", "antiquity ", "mechanical", "intermediate", "sphere", "node", "plywood",
                   "faculty", " punch", "simulation ", "affirm ", "susceptible ", "stereotype ", "wavelength",
                   "poster ", " cylinder", "connotation", "hydrogen", "metaphor", "critique", "algebra", "tumor ",
                   "slot", "chronic"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4752", 1,
                  [" plywood", " spectrum ", "par", " slot", "fusion", "cylinder", " bracket ", "congruent",
                   "chemotherapy", "node"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4753", 1,
                  ["orient", " periodic", "render", " susceptible", "swell ", "convergence", "wavelength", "vertical ",
                   "closure ", "chronic"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4755", 1,
                  ["networks, infrastructures, vehicles and operations", "a high capacity", "Maintenance",
                   " penetrate isolated regions", "promote political unity", "bulky goods", "navigable",
                   "the newest means of transport", "both domestic and international flights", " tankers or trailers"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4757", 2, [
            "Transportation system impacts the climate, accounting for 23% of the world’s greenhouse gas emissions in 2015.",
            "There is great potential for reducing environmental impact by adopting new and efficient technologies, by changing the mode of transport we use or when possible, by choosing options that require little to no transportation at all, like eating local food or telecommuting. Furthermore, governments and companies around the world are increasingly looking to innovate biofuels, electric vehicles, mass transportation and even new types of freight ships."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4759", 2,
                  ["Attacking stadiums, military bases, airports or political rallies.",
                   "Using a powerful radar to identify potentially malicious drones;Firing a net to capture malicious drones after getting a permission, letting them fall down or towing them to a safe landing location."]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4760", 1,
                  ["significantly reduce travelling time", "that will have power plugs and rotating seats",
                   " its share of controversies",
                   "water dripping in several locations, and rusty tracks, flooding and water accumulating under electrical equipment",
                   " the high-speed rail terminus"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4761", 1,
                  ["slash", "C", "friction", "B", "flap", "H", "piston", "G", "pod", "A", "convoluted", "D", "bearings",
                   "F", "airtight", "I", "startup", "J", " compression ", "E"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4762", 0, ["B"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4763", 0, ["C", "D", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4764", 2, [
            "Musk set out his vision for a futuristic super high speed transportation system that would see passenger pods move through a partial vacuum in steel tubes, addressing the two key factors that slow down conventional vehicles: friction and air resistance.",
            "Under Musk’s first Hyperloop proposal, he suggested that compression fans would move air around the passenger pods to minimize drag and create air bearings beneath them, floating them off the surface of the tubes.",
            "With an estimated price tag close to $6 billion, Musk’s first Hyperloop concept never came to fruition, but the impressive idea and potential to link cities in such a direct way sparked intense interest."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4768", 1,
                   ["detect", "intersection", "sensor", "LiDAR", "ultrasonic", "rear", "lane", "collision", "canyon",
                    "odometry"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4769", 1,
                   ["autonomous ", " a driver to get from A to B ",
                    " pick up passengers on demand and take them to their desired destinations",
                    "sophisticated technology", "to see", "at the front and the rear of the vehicle", "on the roof ",
                    "combined and processed in one or more processors", " radar ", "it does not use radio waves",
                    " light rays that are reflected by the objects in the surroundings ",
                    "cameras using artificial intelligence", "detecting obstacles ", "are needed for lane keeping ",
                    "radar ", "forward collision warning and avoidance ",
                    "the fact that the object must be large enough to be detected ",
                    "GPS in highly accurate digital maps ", " tunnels and street canyons", "odometry"]],

    }
    unit_9 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4772", 1,
                  ["auction ", "contour", " fatigue", "implicit", "viable", "depict", "calcium", "novice", "calculus",
                   " loop", "adaptive", "altitude", "mobility", "lump", "stripe", "composite", "allocation", "simplify",
                   "marble", "coordinate", "sustainable", "aggregate", "neuron", "undermine", " hormone", "deviation",
                   "mutation", "oscillation ", "computation", "questionnaire", "container", "volition", "statistically",
                   "parenthesis ", "synthesis", "denominator", "chunk", "syndrome", "portal ", "indicator", "transit",
                   "bundle", "surgeon", "specimen", "infectious", "aluminum", "replication", "alliance", "tempt ",
                   "converge"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4773", 1,
                  ["neuron", "portal ", "calculus", "aluminum", "contour", "indicator", "hormone", "oscillation",
                   "calcium", "loop"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4774", 1,
                  ["composite", "computations", "sustainable", "viable ", "mobility", "aggregate", "novice", " transit",
                   " replication", "allocation"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4776", 1,
                  ["commercial design", "industrialization of consumer products", "early inception",
                   "an expanded awareness", "critical problem solving ", "how it functions ", "value and experience",
                   "multidisciplinary", "a common goal", "craft a solution "]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4777", 2, [
            "Between the 1930s and 1950s, the American designer Raymond Loewy popularized industrial design through his work with the Pennsylvania Railroad, Greyhound, Studebaker and countless domestic product manufacturers bringing elegant design to the masses.",
            "The core ability of a qualified industrial design engineer lies in the creation of plans for manufacturer scale, which involves an understanding of user behaviour, ergonomics, shape, colour, materials, finishes, manufacturing and function. Besides, a keen understanding of how an object sits within a brand, how its benefits may be communicated, its role in society or its impact on other things is also needed."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4779", 2,
                  ["To scatter the sound and give the best listening experience.",
                   "The sound waves can be reflected in all directions.", "It takes a lot of coding (the huge amount and precision of the data)  to get the best results.",
                   "The sound is incredibly transparent and clear."]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4780", 1,
                  ["industrial design and manufacturing", "scale, speed and sustainability",
                   "product and packaging design", "its comprehensive and rich manufacturing chain",
                   "the hub for industrial design in China"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4781", 1,
                  ["chrome", "D", "futuristic", "J", "sleek", "I", "streamlined", "G", "mold", "B", "vinyl", "C",
                   " utilitarian", "H", "plywood", "F", "stamping", "A", "aluminum", "E"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4782", 0, ["C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4783", 0, ["A", "D", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4784", 2, [
            "Innovative production processes like stamping and use of molds allowed them to use new materials for their designs",
            "Americans found great positivity in these futuristic forms.",
            "American industrial design improved America functionally, culturally and intellectually, and exported that around the globe."]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4789", 1,
                                                                                      ["visual weight", "symmetrical",
                                                                                       "mirror image", "asymmetrical",
                                                                                       "proportion", "curved line",
                                                                                       "jagged line", "organic shape",
                                                                                       "geometric shape", "focal"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4790", 1,
                   ["know the mood and message you want to communicate",
                    "choose the proper elements of principles to effectively communicate your design",
                    "the principle of balance", "the way the parts of a composition are placed", "symmetrical balance",
                    "asymmetrical balance", "the principle of contrast",
                    "the differences between the elements of art or the subjects in your design",
                    "the principle of emphasis ", "a focal point or a center of interest in the design",
                    "the principle of movement", "action and it directs your eye throughout the work of art",
                    "the principle of proportion ", "the relationship of the size of objects within a work of art",
                    " the principle of rhythm",
                    "a type of movement that is seen in the repeating of shapes, and colors, or other elements in your work",
                    "rhythm is a repetition or a pattern of shapes, lines, colors or whatever element you are looking at"]],

    }
    unit_10 = {
        "task1": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4799", 1,
                  ["trauma ", "cyclic", "subset", "electron", "trait", "gut", "fiber", "elimination", "algorithm",
                   "elastic", "locus", "resistant", "coefficient", "hedge", " liable", "temporal", "entity ", "diagram",
                   "merge ", "appendix", "axiom", "bucket", "matrix", "hologram", "valid", "probe", "trajectory",
                   "sift", "architect", "theorem", "transmission", " correlate ", "nonetheless", " axis", "scenario",
                   "drift", "chloride", "impact", "gross", "substrate", "subjective", " rotation", "rejection",
                   "compensation", "biodiversity", "plausible", "defect ", "adverse", "franchise", "facade"]],
        "task2": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4802", 1,
                  [" diagram", "facade", "matrix", "algorithm", "substrate", "rotation", " hologram", "electron",
                   "theorem", "fiber"]],
        "task3": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4803", 1,
                  ["elastic", " scenarios", "entities", " defect", "trajectories", "cyclic", " transmission", "locus",
                   "plausible", " subsets"]],
        "task4": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4805", 1,
                  ["framework", "growing urbanization challenges", "intelligent network", "wireless technology",
                   "municipalities", "make better decisions", "traditional urban infrastructure",
                   "pervasive wireless connectivity", "open data", "monetization schemes"]],
        "task5": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4806", 2, [
            "The Internet of things and artificial intelligence will offer the hyper-connected smart cities, technologically equipped to improve the lives of their residents.",
            "In smart cities, the sensors will be installed to analyze the use of electricity in various sectors to optimize energy distribution across the grid; Data Dome will be created as a platform on which public information can be shared to give local players, citizens, and entrepreneurs the means to build the smart city truly for their needs."]],
        "task6": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4808", 2, [
            "Automatic harvesting;Automatic branch trimming;Locating and exterminating weeds;Performing scans and detailed mapping.",
            "Solving labour shortages and ageing farming workforce problems;Operating 24/7;Attracting a new generation of workers."]],
        "task7": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4809", 1,
                  ["entangled particles", "transmit information instantly and completely securely",
                   "have a million times more computing power",
                   "from communications tech, to scientific research, to military advancement",
                   "classified quantum computing project"]],
        "task8": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4810", 1,
                  ["millennial", "C", "mobility", "B", "rant", "I", " trend ", "A", " transact", "E", "workforce", "H ",
                   "digital", "F", "demographics", "D", "unprecedented", "J", "mindset ", "G"]],
        "task9": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4811", 0, ["C"]],
        "task10": ["http://202.119.161.130/StudentSTS/UnitSingleSelect.aspx?UnitTreeID=4812", 0, ["B", "D", "C"]],
        "task11": ["http://202.119.161.130/StudentSTS/UnitEssayQuestion.aspx?UnitTreeID=4813", 2, [
            "The language that you speak, the culture that you subscribe to, the currency that you transact in and where you are physically located are all starting to matter much less. ",
            "Technology, such as big data, wearable devices, collaboration platforms, the Internet of things, and cloud computing are enabling us to work in new ways while keeping us more engaged and productive.",
            "When we think about the future of work, the organizations that can most effectively make this shift from need to want are the ones who will be able to attract and retain top talent. "]],
        "task14": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4817", 1,
                   ["pivot", "nanobot", "cholesterol", "oxygen", "converge", "transcend", " creepy", "amplify",
                    " intelligence explosion", "norm"]],
        "task15": ["http://202.119.161.130/StudentSTS/UnitSelectFill.aspx?UnitTreeID=4818", 1,
                   ["magical, abundant, full of possibilities ", "exponential", "unstoppable ", " Connectivity ",
                    "data ", "a part of us", "converge",
                    " travel virtually to the most amazing places directly from our living room by using our mobile devices",
                    " transcend humanity", " intelligence explosion",
                    "where everyone will need to be amplified or augmented by algorithms",
                    "artificial intelligence and cognitive computing ", " humanity"]],

    }
